### PR TITLE
Wiasliaw/i18n english

### PR DESCRIPTION
**Pull request by wiasliaw**
* i18n
* fix security
* remove template

### CODE REVIEW

**Comment by TseHang** [comment]
Looks good.

Just some questions:
- When I change my browser's language, it is not work, both ssr and export file.
Could you tell me how to test ?

- How you fix security ?

**Comment by TseHang** [comment]
Please resolve the initial detect english language bug~

**Comment by wiasliaw** [comment]
@TseHang  Solved. Thanks for reviewing.

**Review by TseHang — APPROVED** [review]

**Comment by TseHang** [comment]
Thanks, please merge when you are ready!

**Pull request merged**
